### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by DanielaGawehns** [codecheckers/codecheckers#10]
- Name: Daniela Gawehns
- ORCID: 0000-0002-9678-9012 
- Contact: https://www.universiteitleiden.nl/en/staffmembers/daniela-gawehns
- Fields/domains of expertise
  - Clinical Neuropsychology (Developmental Disorders and Dementias)
  - Technology in Healthcare Settings (IoT, Wearables, mobile and stationary sensing)
  - Applied Statistics 

- Programming language(s) and experience levels
  - R (advanced user), Python (basic), MatLab (basic) 

------

How did you hear about CODECHECK?

Reprohack ;-)

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

...

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

...

**Comment by nuest** [comment]
Hi Daniela!

Thanks for your interesting in becoming a codechecker! :heart:

I invited you to the team and added you to the list, will get in touch when we have a paper matching your expertise. Until then, feel free to keep an eye open for interesting preprints in your domain. If you're engaged as reviewer or editor with a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
