### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by gramian** [codecheckers/codecheckers#11]
- Name: Christian Himpe
- ORCID: 0000-0003-2194-6754
- Contact: [himpe.science](https://himpe.science)
- Fields/domains of expertise
  - Applied Mathematics
  - Numerics
  - Model Reduction
- Programming language(s) and experience levels
  - MATLAB/Octave (advanced)
  - Python (basic)

------

How did you hear about CODECHECK?

* Twitter

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

* Code not only needs to be available for reproducibility, but also working. See also our work: [RRR](https://doi.org/bsb2)

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

* I would either be willing to codecheck a submission once a month, or alternatively four times as much as I am reviewed.

**Comment by nuest** [comment]
Hello Christian!

Thanks for your interesting in becoming a codechecker! :heart:

And thanks for the pointer to your article - will take a look! And then you even wrote this when you were sitting around the corner from my place of work...

I invited you to the team and added you to the list, will get in touch when we have a paper matching your expertise. Until then, feel free to keep an eye open for interesting preprints in your domain. If you're engaged as reviewer or editor with a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:

**Comment by gramian** [comment]
Hi,
the point was not having my email in plain text openly published. That's that I guess. But, yes sure use that.

**Comment by nuest** [comment]
Hi there - you're right, and sorry: your entry pointed at your website on purpose, and I should have asked before putting an address in the list and in this thread. I have removed my earlier comment.

Your contact in the list now points at https://www.ulb.uni-muenster.de/bibliothek/ansprechpartner/ansprechpartner-orgaplan.html#innovation instead - that page has a way to reach you, so we don't need to hold an address ourselves. Let me know if you'd prefer a different page. Thanks for the nudge, and sorry for the noise!
