### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by LindaNab** [codecheckers/codecheckers#12]
- Name: Linda Nab
- ORCID: https://orcid.org/0000-0002-1821-7246 
- Fields/domains of expertise
  - Epidemiology/Medical statistics
- Programming language(s) and experience levels
  - R
------

**Comment by nuest** [comment]
Hi @LindaNab !

Thanks for your interesting in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer or editor with a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
