### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by bhym** [codecheckers/codecheckers#14]
- Name: Bruno Hay Mele
- ORCID: 0000-0001-5579-183X 
- Contact: bruno.haymele@szn.it
- Fields/domains of expertise
  - Ecology; Biostatistics; Individual Based Models; Process-based Models, Multiscale Tissue modelling
- Programming language(s) and experience levels
  - R (advanced)
  - Python (basic)
  - C++ (intermediate)

------

How did you hear about CODECHECK?

Reading about the Imperial College COVID model [here](https://www.nature.com/articles/d41586-020-01685-y)

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

To support reproducible research, of course. And to improve my coding skills as well.

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?
My rough estimate at the moment: ~5hrs/week

**Comment by nuest** [comment]
Hi Bruno!

Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
