### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by wwaites** [codecheckers/codecheckers#16]
- Name: William Waites
- ORCID: 0000-0002-7759-6805
- Contact: wwaites at inf dot ed dot ac dot uk
- Fields/domains of expertise
  - networks and complex systems
  - epidemiological population models
  - evolutionary game theory
  - information theory
  - synthetic biology modelling
  - unix systems engineering & telecommunications
- Programming language(s) and experience levels
  - functional languages (Haskell, ML, LISP)
  - utilitarian languages (Python, Go)
  - systems programming (C)
  - bourne shell, make, awk, etc
  - domain-specific languages like Kappa
  - exposure to and small projects in Scala, C++, etc.
------

I've been writing software since the early 1990s and have used most mainstream and some obscure programming languages at one time or another. Clarity of exposition can be as important as reproducibility: it is unclear to me if there is much value in an obfuscated or poorly structured piece of code that can reproduce a diagram unless it is an entry in an obfuscated software writing competition. An important part of the review process should ideally be to be able to check that the software does what the corresponding paper says it does, not merely that it can compile and run. This is a fairly high barrier...

How did you hear about CODECHECK?

Daniel Nüst contacted me on the Twitter after I ranted a bit about Neil Ferguson's epidemiological model famously used in the UK

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

I believe that where science is based on software, the software is as important as the paper that is written about it. I have also inherited "academic" codebases from time to time and would like to encourage a culture that spares our descendants that pain.

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

Given the importance, I would say about equal. However, I think that the paper and the code should be reviewed together. That would be much more valuable than simply reviewing the code on its own.

**Comment by just-s-i-d** [comment]
Name:Siddharth Paneri
Currently pursuing B.tech in Computer science .
Love to do programming 
Learnt c++
And currently Learning Python programming

**Comment by nuest** [comment]
@just-s-i-d Please open a new issue - thanks!

**Comment by nuest** [comment]
Hi Willian,

Thanks for not putting aside my tweet, and your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:

I agree with you that ideally a code check / execution and the review go hand in hand, however, one of our core assumptions is that it might be easier to match skillsets and find volunteers when the reviewer and the CODECHECKER are two distinct roles, see https://codecheck.org.uk/process/#dimensions-of-codecheck. _Happy to get your feedback on that!_
