### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by j-berg** [codecheckers/codecheckers#17]
```csv
Jordan Berg,@j-berg,0000-0002-5096-0558,jordan.berg<at>biochem.utah.edu,"bioinformatics, computational biology, network biology, rna-seq analysis, proteomics analysis, metabolomics analysis, ribosome profiling analysis","R (intermediate), Python (expert), Javascript (intermediate), C++ (beginner), Julia (beginner)"
```
...

How did you hear about CODECHECK? Nature news

...

What is your motivation to contribute to CODECHECK? Giving back to community and supporting reproducible research/open science

...

How much time would you be able to spend on forechecking: ~2hr/wk? Variable depending on need and frequency of requests to code check

...

**Comment by nuest** [comment]
Hi @j-berg!

Thanks for your interest in becoming a codechecker! :heart: And my sincere apologies for the delay in handling your registration.

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:

**Comment by j-berg** [comment]
No worries, thanks! Excited to be part of the community! I will keep an eye out for interesting papers!
