### ISSUE TITLE
Join as codechecker

### ISSUE THREAD

**Issue by GiulioCentorame** [codecheckers/codecheckers#2]
Giulio Centorame
0000-0003-1939-2721
Genetic epidemiology, psychiatric genetics, R

**Comment by nuest** [comment]
Welcome @GiulioCentorame !

While I'm still setting up a proper process, would you be so kind to provide some contact information (institutional or personal website), since your ORCID also does not have that. Thanks!

**Comment by GiulioCentorame** [comment]
Yes! Thank you, I did not notice my ORCID profile was that empty. I added my info to it, you can find my personal website [here](giuliocentora.me). 
Cheers

**Comment by nuest** [comment]
Thanks Giulio!
