### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by IainDaviesMaths** [codecheckers/codecheckers#21]
Your data:

```csv
Iain Davies,@IainDaviesMaths,0000-0002-5361-6285,see ORCID page,"neuroscience","MATLAB (intermediate), familiar with Python and C"
```

------

How did you hear about CODECHECK?

Through a Summer research project with Stephen Eglen

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

Gaining experience with academic papers and improving my coding skills.

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

I've got 8 weeks in Summer 2020.

**Comment by sje30** [comment]
hi @nuest 
please can you add Iain to the group, so that he can clone a repo and start his first codecheck.

**Comment by sje30** [comment]
hi @nuest 
is this something I can do to add Iain to the codecheckers?  (What do I need to do?)  Iain has a codecheck from Manuel almost ready to go (the R package worked).

**Comment by nuest** [comment]
Hi @IainDaviesMaths !

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). I look forward to see what you'll build over the summer!
