### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by ajwills72** [codecheckers/codecheckers#22]
Your data:

```csv
Andy Wills,@ajwills72,0000-0003-4803-0367,andy@willslab.co.uk,"cognitive psychology, cognitive science, categorization, learning","R, Python, C/C++, bash"
```

------

How did you hear about CODECHECK?

Stephen Eglen's talk on 2020-09-08

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

Supporting open science, curiosity

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

I should be able to accommodate one codecheck per month at present.

**Comment by nuest** [comment]
Hello Andy!

Thanks for your interest in becoming a codechecker! :heart:
It's great to have people sign up after talks by the initiative's members.

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
