### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by chenyenchung** [codecheckers/codecheckers#23]
Your data:

```csv
Yen-Chung Chen,@chenyenchung,0000-0002-8529-1251,see ORCID page,"developmental biology,single-cell profiling","R,Python"
```

------

How did you hear about CODECHECK?

I heard about CODECHECK at the Virtual Brainstorming Day for ECRs hosted QUEST Center in Berlin. Naomi Penfold, a community manager kindly directed me here.
...

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

Supporting reproducible research and open science (and it will also be nice for the community to have tools checked anyway)

...

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

I can spend time reviewing code comparable to standard reviewing process.

...

**Comment by nuest** [comment]
Hello Yen-Chung,

Thanks for your interest in becoming a codechecker! :heart:

@npscience thank you so much for mentioning the project!

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:

Also, I'm actually based in Berlin, so it would be great to maybe have, at some point when sensible, have an in-person meeting at QUEST.

**Comment by chenyenchung** [comment]
Hi Daniel, 
    Thank you for adding me! I'll keep an eye on preprints that I could do a community CODECHECK and looking forward to chances to integrate code review into the workflow of publishers and journals.

    I am currently based in New York, but when I get a chance to visit Berlin, it would be great to meet in person!
