### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by ethanbb** [codecheckers/codecheckers#24]
Your data:

```csv
Ethan Blackwood,@ethanbb,0000-0002-3049-0640,see ORCID page,"ephys, neuroimaging, machine learning, ","**Python, **MATLAB, **C++, *LabVIEW, *Javascript, PHP, Java, Bash"
```

------

How did you hear about CODECHECK?

I think I've run across it before, but most recently through this article while searching around to find out if there were any 3rd parties doing scientific code review: https://philbull.wordpress.com/2020/05/10/why-you-can-ignore-reviews-of-scientific-code-by-commercial-software-developers/

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

- Supporting reproducible research & reducing the amount of bad scientific code out there
- Gaining experience in helping scientists with their code

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

Not sure, maybe 3-4 hours/week on average

**Comment by nuest** [comment]
Hi Ethan!

Thank you so much for signing up, and for the link to the article - I wasn't aware of it!

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:

**Comment by ethanbb** [comment]
Thanks Daniel, looking forward to getting started!
