### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by yanxianl** [codecheckers/codecheckers#25]
Your data:

```csv
Yanxian Li,@yanxianl,0000-0001-8529-2564,yanxianl@nmbu.no,"aquaculture, nutrition, microbiome","Bash (basic), python (basic), R (intermediate)"
```

------

How did you hear about CODECHECK?
**Twitter.**
...

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.
**Supporting reproducible research/open science.**
...

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?
**1-2 days.**
...

**Comment by nuest** [comment]
Thanks @yanxianl for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
