### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by alberto-antonietti** [codecheckers/codecheckers#27]
Your data:

```csv
Alberto Antonietti,@alberto-antonietti,0000-0003-0388-6321,see ORCID page,"computational neuroscience, spiking neural networks, brain simulation, neuroengineering, machine learning","Python (intermediate/advanced), C++ (intermediate, do not use if often nowadays), MATLAB (proficient, but now I mostly use Python"
```

------

How did you hear about CODECHECK?

I saw it on Twitter

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

I am a strong supporter of reproducible and open research, as Reviewer I always suggest sharing data and code to check them, I try to do the same with my own work.

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

Ideally, it would be 1 paper reviewed = 1 code reviewed. Of course, checking the code could require ~2/3 more time than just reviewing the paper. Since I review on average 3-4 papers/months, I would be able to _codecheck_ ~1 per month.

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

Unfortunately I didn't find an email on your ORCID profile - can you please check? Thanks - we simply want another option to reach you besides GitHub.

I'll add you to the list then asap, just ping me here.

**Comment by alberto-antonietti** [comment]
Hi @nuest ! You are right, it was not public, but private. I have changed permissions right now 🤙

**Comment by nuest** [comment]
Thanks!

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
