### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by dpshelio** [codecheckers/codecheckers#28]
Your data:

```csv
David Pérez-Suárez,@dpshelio,0000-0003-0784-6909,see ORCID page,"Research Software Engineering, multi-discipline, Astrophysics, image processing, simulations","Python, R, C++, Fortran"
```

------

**How did you hear about CODECHECK?**

Through the Code Review Community and [ReproHacks](https://reprohack.github.io/reprohack-hq/), and finally from the [F1000Research paper](https://f1000research.com/articles/10-253/v1).

**What is your motivation to contribute to CODECHECK?**

As a young researcher, I suffered trying to reproduce papers that were not reproducible with the information provided. That should not happen! Now, as an RSE I'm involved in different activities to promote reproducibility and CodeCheckers helps in a simple way to give a 👍 to the papers at publishing time.

**How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?**

An afternoon per month.

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:

**Comment by nuest** [comment]
Hi there! Small housekeeping on your entry in [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv): your registration said "see ORCID page", but there is no longer a readable email on [your ORCID profile](https://orcid.org/0000-0003-0784-6909), so I took `d.perez-suarez@ucl.ac.uk` from https://david.ps (where https://dpshelio.github.io now redirects) instead - it is obfuscated on the page, so apologies if I reassembled it wrongly.

Please let me know if that address is still current - and if you re-add a public email to ORCID, even better, then we can point back there. Thanks!

**Comment by dpshelio** [comment]
That's the right one! Thanks for making the effort to find it. I thought it was visible on the orcid page (or it was back then).
I've made the email on ORCID visible.
