### ISSUE TITLE
Join as a codechecker

### ISSUE THREAD

**Issue by NathanSkene** [codecheckers/codecheckers#3]
name: Nathan Skene
    ORCID: 0000-0002-6807-3180
    fields of expertise: single cell genomics; psychiatric genetics

**Comment by nuest** [comment]
Welcome @NathanSkene ! While I'm still setting up a proper process, would you be so kind to tell us what programming languages your are familiar with? _Ideally every codechecker should be able to follow the instructions_, but of course you can be more effective if you know the language.

**Comment by NathanSkene** [comment]
R mostly. If they've got NextFlow workflows could do that as well.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nuest** [comment]
Hi there! Small housekeeping on your entry in [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv): your registration said "see ORCID page", but there is no longer a readable email on [your ORCID profile](https://orcid.org/0000-0002-6807-3180), so I took `n.skene@imperial.ac.uk` from the About section of https://www.neurogenomics.co.uk instead.

Please let me know if you'd prefer a different address (the page also lists `nskene@ic.ac.uk`) - and if you re-add a public email to ORCID, even better, then we can point back there. Thanks!
