### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by dokato** [codecheckers/codecheckers#30]
Your data:

```csv
Dominik Krzemiński,@dokato,0000-0003-4568-0583,https://www.zoo.cam.ac.uk/directory/dominik-krzeminski,"neuroscience,psychophysics,dynamical models","Python,R,Matlab-advanced,JavaScript-intermediate,C++,Java-basics"
```

------

How did you hear about CODECHECK?

Stephen Eglen's talk at Open Research Working Group '20.

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

I want to support reproducible science as I came across many reproducibility problems myself in my early career research.

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

As much as needed.

**Comment by sje30** [comment]
hi @nuest 
can you remind me what I need to do to add Dominik?

**Comment by nuest** [comment]
@sje30 Sorry for the delay - great you could get a few new people on board! We're really building up the capacity to move forward! Re. the steps, everything I do is listed in the README.

------

@dokato Thanks for your interest in becoming a codechecker! :heart: Apologies for the delay, I am on parental leave until Spring 2022.

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
