### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by Xa4P** [codecheckers/codecheckers#31]
------

How did you hear about CODECHECK?

From the Open Science Community of Twente

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

All of those: improving coding skills, giving back to community, supporting reproducible research/open science

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

Approximately 3-4 hours per check

**Comment by nuest** [comment]
@Xa4P Thanks for your interest in becoming a codechecker! Apologies for the delay, I'm currently on parental leave and this is so far a (growing) side project.

**Would you be so kind and to update your information with an email or where we can find one?** Your ORCID page does not have an email, and neither did a spot one on the linked uni profile page. Thanks!

**Comment by Xa4P** [comment]
@nuest I have now made my email address visible for everybody on my ORCID page. Best, Xavier

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
