### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by eirini-zormpa** [codecheckers/codecheckers#33]
Your data:

```csv
Eirini Zormpa,@eirini-zormpa,0000-0002-6902-7768,e.zormpa@tudelft.nl,"psycholinguistics","R"
```

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart: Apologies for the delay, I am on parental leave :baby: until Spring 2022.

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
