### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by lenarddome** [codecheckers/codecheckers#34]
Your data:

```csv
Lenard Dome,@lenarddome,0000-0001-7487-1974,lenard.dome@plymouth.ac.uk,"formal computational modelling, categorization, contingency learning","R (advanced), Rcpp (intermediate), RcppArmadillo (intermediate), Python (basic)"
```

------

How did you hear about CODECHECK?

- Open Research Working Group (ORWG) virtual meeting 08/09/20
- Supervisor

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

1. Nurture open science practices.
2. Helping people to write code that can be understood by people who were not involved in writing said code.
3. Push for properly documenting code and research software

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

2-4 hours/week

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart: Apologies for the delay, I am on parental leave :baby: until Spring 2022.

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
