### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by mirusak94** [codecheckers/codecheckers#35]
Your data:

```csv
Miroslava Jindrova,@mirusak94,0000-0002-9924-6427,miroslava.jindrova@zi-mannheim.de,"neuroscience, fMRI, neurofeedback", "Matlab, R, Python (basic)"
```

------

How did you hear about CODECHECK?

...Read a paper about it (Nüst&Eglen, 2021) that I probably heard of on some open science meetup.

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

...Support open and reproducible science, improve coding skills

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

...Did not review any papers yet. I assume that I would accept a codechecking-offer if I know that my time schedule allows that at that time point.

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
