### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by romeopenheiro** [codecheckers/codecheckers#36]
Your data:

```csv
Romeo Penheiro,@romeopenheiro,0000-0001-5267-9121,see ORCID page,"psychology, cognitive psychology, neuroscience","R"
```

------

How did you hear about CODECHECK?

I heard about CODECHECK at the Toronto Workshop on Reproducibility

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

I am very interested in supporting reproducible practices in scientific research.

**Comment by romeopenheiro** [comment]
email: romeopenheiro@cmail.carleton.ca
ORCID: https://orcid.org/0000-0001-5267-9121

**Comment by nuest** [comment]
Thanks - now that it's public on ORCID, I put my money on you updating it there :-)

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
