### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by kingjml** [codecheckers/codecheckers#37]
Your data:

```csv
Josh King,@kingjml,0000-0002-0353-8987,see ORCID page,"cryosphere, remote sensing, GIScience","Python, R, Matlab"
```

------

How did you hear about CODECHECK?

Stephen Eglen's excellent talk at the Toronto Reproducibility Workshop
...

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

Support reproducibility in climate and Arctic sciences. Improve understanding applied and operational code. 

...

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

1 review per month.
...

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
