### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by ArianeMora** [codecheckers/codecheckers#38]
Your data:

```csv
Ariane Mora,@arianemora,0000-0003-1331-8192,ariane.n.mora@gmail.com,"bioinformatics, nextgen sequencing, machine learning, rna-seq, cancer, tensorflow, genetics, development, chip-seq, nanopore, dna methylation, wgbs, epigenetics","R (intermediate), python (advanced), c (intermediate), Java (advanced)"
```

------

How did you hear about CODECHECK?

Email from GigaScience. 
...

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting 
reproducible research/open science, etc.

Supporting reproducibility. 
...

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?
Not sure.
...

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:

**Comment by ArianeMora** [comment]
Thanks! Just so I'm clear on the workflow for community codechecking (e.g. a paper from bioRxiv): 1) get in contact with the authors 2) do the codecheck 3) open an issue on the codecheck github [like so](https://github.com/codecheckers/register/issues/40), 4) let the authors know? Or switch over 3/4 so that they can re-run/fix any issues (if it isn't reproducible) given it's just a preprint?
Thanks again! Love the idea :) hopefully means that we'll have more published code that runs first time.
