### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by SaranjeetKaur** [codecheckers/codecheckers#40]
Your data:

```csv
Saranjeet Kaur Bhogal,@SaranjeetKaur,0000-0002-7038-1457,kaur.saranjeet3@gmail.com, "Statistics", "R, Julia"
```

------

How did you hear about CODECHECK?
- At Keynote on Code Review at Collaborations Workshop 2022.
...

What is your motivation to contribute to CODECHECK?
- Supporting reproducible research & open science and giving back to the community.
...

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?
- About an hour a week, as an when available.
...

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
