### ISSUE TITLE
Register Raniere Silva as codechecker

### ISSUE THREAD

**Issue by rgaiacs** [codecheckers/codecheckers#42]
Your data:

```csv
Raniere Silva,@rgaiacs,0000-0002-8381-3749,"operation research,medical image,radiograph,machine learning,convolutional neural network","Python, R"
```

------

How did you hear about CODECHECK?

From Collaborations Workshop.

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

Promote reproducible research.

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

1h/week

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:

**Comment by sje30** [comment]
we need an email for you @rgaiacs !

**Comment by rgaiacs** [comment]
You can use raniere.silva@my.cityu.edu.hk
