### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by jaibalani** [codecheckers/codecheckers#45]
Your data:

```csv
Jai Balani,@jaibalani,0009-0003-4628-6155,[jai.balani@gmail.com](https://www.linkedin.com/in/jaibalani/),"Data Privacy, Data Security, Data Engineering, Algorithms, AI","Python, SQL, Scala, Java"
```

------

How did you hear about CODECHECK?

From the Peer Review Week

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

Belong to a community, learn from other codecheckers

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

2-3 hours a week

**Comment by jaibalani** [comment]
Hi @nuest could you please help resolve this registration request?

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
