### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by priyambial123** [codecheckers/codecheckers#47]
Your data:

```csv
priyambial123@github.com
```

------

How did you hear about CODECHECK?
From a colleague working in University of Basel
...

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.
Open-science has been my interest and I would like to contribute to the community as well as learn skills to contribute
...

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?
1-2 hrs
...

**Comment by nuest** [comment]
Hi @priyambial123 !

Can you please update your data to include all fields from the template? Thanks!

```csv
name,@GitHub-handle,ORCID ID (not url),contact (or "see ORCID page"),"fields","languages"
```

**Comment by nuest** [comment]
@priyambial123 Just a friendly reminder: we need a bit more information to add you to the list. Thanks!

**Comment by nuest** [comment]
I'm a bit confused by the `@github.com` email address, though the user account does have a few (non informative) repositories. Still closing this - happy to reopen when @priyambial123 finds the time to provide the required information!
