### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by cforgaci** [codecheckers/codecheckers#48]
```
Claudiu Forgaci,@cforgaci,0000-0003-3218-5102,see ORCID page,"urban analytics, geospatial analysis, text analysis","R (advanced), Python (intermediate)"
```
------

How did you hear about CODECHECK?

- In a lecture given by Daniel Nüst.

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

- Supporting reproducible science and improving coding skills.

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

- Approx. 1 hour per assignment

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

Unfortunately I didn't find an email via your ORCID profile or personal page with an email linked on it - can you please check? Thanks! We simply want another option to reach you besides GitHub.

I'll add you to the list then asap, just ping me here.

**Comment by cforgaci** [comment]
Feel free to use my institutional email address c.forgaci@tudelft.nl

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
