### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by delapazruiz** [codecheckers/codecheckers#49]
Your data:

```csv
Néstor Codechecker,@delapazruiz,0000-0002-8941-4677,see ORCID page,"geospatial, models, water&health","R, Netlogo"
```

------

How did you hear about CODECHECK?

From my supervision team at University of Twente, Netherlands.

...

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to the community, supporting reproducible research/open science, etc.

To support the growth of open science as the new standard and to recognize peer colleagues for their will to share knowledge with society.

...

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

Occasionally, during weekends.

...

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

Unfortunately I didn't find an email via your ORCID profile or personal page linked on it - can you please check? Thanks! We simply want another option to reach you besides GitHub.

I'll add you to the list then asap, just ping me here.

**Comment by delapazruiz** [comment]
@nuest Thank you very much for the reaction. I noticed that my email contact in ORCID was private. Now, my contact information should be public. I share my institutional email: n.delapazruiz@utwente.nl.
