### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by mstimberg** [codecheckers/codecheckers#5]
- Name: Marcel Stimberg
- ORCID: [0000-0002-2648-4790](http://orcid.org/0000-0002-2648-4790)
- Contact: http://www.computational-neuroscience-of-sensory-systems.org/people/marcel-stimberg/
- Fields/domains of expertise
  - Computational Neuroscience
  - Neuroinformatics
- Programming language(s) and experience levels
  - Python (expert)
  - C/C++/CUDA (intermediate)
  - R (basic)

**Comment by nuest** [comment]
Hi Marcel! Thanks for your interest to become a codechecker :tada: !

I added you to the list, will get in touch when we have a paper matching your expertise. Until then, feel free to keep an eye open for interesting preprints in your domain. If you're engaged as reviewer or editor with a journal, we'd be happy to chat with you about establishing CODECHECKs :muscle:
