### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by SilvinWillemsen** [codecheckers/codecheckers#50]
Your data:

```csv
Silvin Willemsen,@SilvinWillemsen,0000-0002-4062-5473,silvinwillemsen@gmail.com,"audio technology, physical modelling, digital signal processing, acoustics, virtual reality","C++ (highly proficient), MATLAB (highly proficient), Unity / C# (proficient), Python (know how to run code, not proficient)"
```

------

How did you hear about CODECHECK?

I attended the CODECHECK-NL workshop @ TU Delft on May 30th, 2024. 

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

I think CODECHECK philosophy is very much in line with my own. As code (and data) becomes a bigger and bigger part of the contributions we make as scientists, I feel like this needs an additional "review", at the very least in terms of executability. I believe that if one has worked for months/years on a publication about a piece of code, but it can't be run due to a few (easily fixable) lines of code, the impact of ones work suffers immensely. This is something that, in my eyes, can be relatively easily fixed through the CODECHECK procedure.

All in all, I believe that CODECHECK can drastically improve the impact of scientific work currently done, and thereby improve science as a whole. 

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

I think I would be able to do more codechecks than reviews. (Maybe 1 or 2 a month) This is mainly due to my understanding that the CODECHECK should only be focused on executability of the code, not reproducability of the results (or scientific validity for that matter).

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
