### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by rbravos** [codecheckers/codecheckers#51]
Your data:

```csv
Ramiro Bravo,@rbravos,009-0000-7399-1448,ramiro.bravo@manchester.ac.uk & ramirobravo@gmail.com, "digital health, health data management, data management, data analytics and visualisations, data engineering, FAIR data","Python (Intermediate), SQL (expert), Data analysis and visualisations with Streamlit, R (beginner), C# (Intermediate), REDCap (Intermediate), PowerBI"
```

------

How did you hear about CODECHECK?
I heard from Limor Peer from Research Data Alliance, Reproducibility Interest Group (IG). 
...

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.
I would like to increase Open Science in research. Also, I would like to provide the scientific community and the public a way to verify the findings of research publications in support to the FAIR data principles specifically for Reusable (R) which aligns with reproducibility of research. I think data is not reusable, if I can not reproduce the findings.
...

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?
I would like to know more about the process and the needs. I can start contributing 1 to 2 hours a week. Thank you
...

**Comment by nuest** [comment]
Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-workflow). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
