### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by stm** [codecheckers/codecheckers#6]
- Name: Stefan Mayer
- ORCID: 0000-0003-0034-7090 
- Contact: see ORCID page
- Fields/domains of expertise
  - marketing, consumer psychology, image analytics, machine learning
- Programming language(s) and experience levels
  - R, Python, Matlab

**Comment by nuest** [comment]
Hi Stefan! Thanks for your interest to become a codechecker :tada: !

I added you to the list, will get in touch when we have a paper matching your expertise. Until then, feel free to keep an eye open for interesting preprints in your domain. If you're engaged as reviewer or editor with a journal, we'd be happy to chat with you about establishing CODECHECKs :muscle:

**Comment by nuest** [comment]
Hi there! Small housekeeping on your entry in [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv): your registration said "see ORCID page", but there is no longer a readable email on [your ORCID profile](https://orcid.org/0000-0003-0034-7090), so I took `stefan.mayer@uni-tuebingen.de` from your university page at https://uni-tuebingen.de/en/148617 instead (it is spam-protected there, so apologies if I reassembled it wrongly).

Please let me know if you'd prefer a different address - and if you re-add a public email to ORCID, even better, then we can point back there. Thanks!
