### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by jmoldon** [codecheckers/codecheckers#7]
- Name: Javier Moldon
- ORCID: 0000-0002-8079-7608 
- Fields/domains of expertise
  - Astronomy and astrophysics
- Programming language(s) and experience levels
  - python (advanced)

**Comment by nuest** [comment]
Hi Javier! Thanks for your interest to become a codechecker! :tada: 

_Can you please tell me a public email address?_ Or add one to your ORCID profile (preferred). Thanks!

------


We'll be keeping an eye out for astronomy papers to codecheck - feel free to suggest "popular" or widely cited papers from your domain for a community codecheck, so you have examples to show your peers.

**Comment by nuest** [comment]
@jmoldon Friendly ping - would be great to get you on the list.

**Comment by jmoldon** [comment]
Thank you. This could be a good place to find my contact information: https://jmoldon.github.io/
The contents are not very up to date, so I have emptied them, but the contact info is the current one

**Comment by nuest** [comment]
Thanks! You're in the register now.

Besides checking "classic papers" from astronomy, you can also mention CODECHECK as part of your work as author, reviewer, or editor. Let us know if you have any questions!

**Comment by nuest** [comment]
Hi there! Small housekeeping on your entry in [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv): it pointed at https://jmoldon.github.io/, which does not resolve any more (nor does https://www.iaa.csic.es/~jmoldon/, linked on [your ORCID profile](https://orcid.org/0000-0002-8079-7608)). I found `jmoldon@iaa.es` at the bottom of https://home.iaa.csic.es/~jmoldon/ and noted that instead.

Please let me know if you'd prefer a different address - and if you add a public email to ORCID, even better, then we can point back there. Thanks!

**Comment by jmoldon** [comment]
The information is now correct. Thanks
