### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by cgranell** [codecheckers/codecheckers#8]
- Name: Carlos Granell
- ORCID: 0000-0003-1004-9695
- Contact: @cgranell
- Fields/domains of expertise
- Spatial analysis, GIScience
- Programming language(s) and experience levels
- R (intermediate), spatial data analysis with Python (basic)

**Comment by nuest** [comment]
Welcome @cgranell - great to see a familiar face here.

Thanks for your interesting in becoming a codechecker! :heart:

I invited you to the team and added you to the list, will get in touch when we have a paper matching your expertise. Until then, feel free to keep an eye open for interesting preprints in your domain. If you're engaged as reviewer or editor with a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:

**Comment by nuest** [comment]
Hi there! Small housekeeping on your entry in [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv): your registration said "see ORCID page", but there is no longer a readable email on [your ORCID profile](https://orcid.org/0000-0003-1004-9695), so I took `carlos.granell@uji.es` from the GEOTEC staff page at https://geotec.uji.es/staff/ instead. The other site linked on your ORCID, http://www.carlosgranell.eu, does not resolve any more - you may want to update that there.

Please let me know if you'd prefer a different address - and if you re-add a public email to ORCID, even better, then we can point back there. Thanks!

**Comment by cgranell** [comment]
Hi Daniel. That email is ok. I updated my homepage in my ORDIC profile too: https://cgranell.github.io/
