### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by Christian-T** [codecheckers/codecheckers#9]
- Name: Christian Maximilian Thurn
- ORCID: https://orcid.org/0000-0002-5942-3273
- Contact: ...
- Fields/domains of expertise
  - Psychology, Science Education, Conceptual Change Theories, Frequentist statistics, Multilevel Modelling, Network Analysis
- Programming language(s) and experience levels
  - R (intermediate)

------

How did you hear about CODECHECK?

- R Weekly newsletter from 17.05.2020

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

I support open science initiatives and want to contribute to make science more reproducible and reliable. 

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

not very much (Maybe one check every 2 months or so)

**Comment by nuest** [comment]
Hi @Christian-T !

Thanks for your interesting in becoming a codechecker! :heart: And thank for for filling out the extra questions :+1: 

I invited you to the team and added you to the list, will get in touch when we have a paper matching your expertise. Until then, feel free to keep an eye open for interesting preprints in your domain. If you're engaged as reviewer or editor with a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
